WebStock/Models/ErrorViewModel.cs
namespace WebStock.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebStock/Models/InformeLote.cs
namespace WebStock.Models
{
    public class InformeLote
    {
        public int Lote { get; set; }
        public string Producto { get; set; }
        public int Cantidad { get; set; }
        public string Fabricacion { get; set; }
        public string Expiracion { get; set; }
        public string Provedor { get; set; }
        public InformeLote() { }
    }
}

WebStock/Models/ModelEntradaProducto.cs
namespace WebStock.Models
{
    public class ModelEntradaProducto
    {
        public Product? producto { get; set; } = new Product();
        public string? messaje { get; set; } = "";
    }
}

WebStock/Models/ModelSalidaProducto.cs
namespace WebStock.Models
{
    public class ModelSalidaProducto
    {
        public SalidaInventario? Salida { get; set; } = new SalidaInventario();
        public string? messaje { get; set; } = "";
    }
}

WebStock/Models/Product.cs
namespace WebStock.Models
{
    public class Product
    {
        public string? Producto { get; set; } = "";
        public int? NumeroLote { get; set; } = 0;
        public int? Cantidad { get; set; } = 0;
        public string? FechaFabricacion { get; set; } = "";
        public string? Provedor { get; set; } = "";
        public string? FechaCaducidad { get; set; } = "";

        public Product() { }

      
    }
}

WebStock/Models/SalidaInventario.cs
namespace WebStock.Models
{
    public class SalidaInventario
    {
        public int NumLote { get; set; }
        public string Producto { get; set; } = "";
        public int Cantidad { get; set; }
        public string Fecha_salida { get; set; } = "";
        public string Destino { get; set; } = "";

        public SalidaInventario() { }
    }
}

WebStock/Controllers/FaltantesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using WebStock.Models;

namespace WebStock.Controllers
{

    public class FaltantesController : Controller
    {
        private readonly HttpClient _HttpClient;
        private readonly string APIUrl;

        public FaltantesController(IConfiguration IConfiguration, HttpClient HttpClient) {
            APIUrl = IConfiguration.GetValue<string>("APIUrl");
            _HttpClient = HttpClient;
        }

        public async Task<ActionResult> Faltantes()
        {
            List<InformeLote> faltantes = new List<InformeLote>();
            HttpResponseMessage response = await _HttpClient.GetAsync($"{APIUrl}ProductWebService/GetFaltantes");
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            faltantes = JsonConvert.DeserializeObject<List<InformeLote>>(responseBody);

            return View(faltantes);
        }
    }

}

WebStock/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebStock.Models;

namespace WebStock.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebStock/Controllers/InventarioController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http;
using WebStock.Models;

namespace WebStock.Controllers
{
    public class InventarioController : Controller
    {

        private readonly HttpClient _HttpClient;
        private readonly string APIUrl;

        public InventarioController(IConfiguration IConfiguration, HttpClient HttpClient)
        {
            APIUrl = IConfiguration.GetValue<string>("APIUrl");
            _HttpClient = HttpClient;
        }
        // GET: InventarioController
        public ActionResult Inventario()
        {
            return View();
        }

        [HttpGet]
        public async Task<List<InformeLote>> GetInfoLote(int numLote)
        {
            HttpResponseMessage response = await _HttpClient.GetAsync($"{APIUrl}ProductWebService/GetInfoLote?NumLote=" + numLote);
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            List<InformeLote>? InfoLotes = JsonConvert.DeserializeObject<List<InformeLote>>(responseBody);
            return InfoLotes;
        }
    }
}

WebStock/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System.Data;
using System.Text.Json.Serialization;
using WebStock.Models;

namespace WebStock.Controllers
{
    public class ProductController : Controller
    {
        private readonly HttpClient _HttpClient;
        private readonly string APIUrl;

        public ProductController(IConfiguration IConfiguration, HttpClient HttpClient)
        {
            APIUrl = IConfiguration.GetValue<string>("APIUrl");
            _HttpClient = HttpClient;
        }
        public ActionResult Products()
        {
            return View(new ModelEntradaProducto());
        }

        [HttpGet]

        public async Task<List<string>> ProductsList()
        {
            HttpResponseMessage response = await _HttpClient.GetAsync($"{APIUrl}ProductWebService/GetProductos");
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            List<string>? products = JsonConvert.DeserializeObject<List<string>>(responseBody);
            return products;
        }

        public async Task<List<string>> ProvedorList()
        {
            HttpResponseMessage response = await _HttpClient.GetAsync($"{APIUrl}ProductWebService/GetProvedores");
            response.EnsureSuccessStatusCode();
            var responseBody = await response.Content.ReadAsStringAsync();
            List<string>? provedores = JsonConvert.DeserializeObject<List<string>>(responseBody);
            return provedores;
        }


        [HttpPost]
        public async Task<IActionResult> CreateProduct(ModelEntradaProducto Entradaproduct)
        {
            try
            {
                HttpResponseMessage response = await _HttpClient.PostAsJsonAsync($"{APIUrl}ProductWebService/", Entradaproduct.producto);
                response.EnsureSuccessStatusCode();

                string resultado = await response.Content.ReadAsStringAsync();
                ModelEntradaProducto ModeloRsepuesta = new();
                ModeloRsepuesta.messaje=resultado;
                return View("Products",ModeloRsepuesta);
            }
            catch
            {
                return View();
            }
        }

       
    }
}

WebStock/Controllers/SalidasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using WebStock.Models;

namespace WebStock.Controllers
{
    public class SalidasController : Controller
    {

        private readonly HttpClient _HttpClient;
        private readonly string APIUrl;

        public SalidasController(IConfiguration IConfiguration, HttpClient HttpClient) {
            APIUrl = IConfiguration.GetValue<string>("APIUrl");
            _HttpClient = HttpClient;
        }

        public ActionResult Salidas()
        {
            return View(new ModelSalidaProducto());
        }

        [HttpPost]
        public async Task<IActionResult> MoverProducto(ModelSalidaProducto SalidaProducto)
        {
            try
            {
                HttpResponseMessage response = await _HttpClient.PostAsJsonAsync($"{APIUrl}ProductWebService/MoverProducto", SalidaProducto.Salida);
                response.EnsureSuccessStatusCode();

                string resultado = await response.Content.ReadAsStringAsync();
                ModelSalidaProducto ModeloRepuesta = new();
                ModeloRepuesta.messaje = resultado;
                return View("Salidas", ModeloRepuesta);
            }
            catch
            {
                return View();
            }
        }
    }
}

WebStock/Views/Faltantes/Faltantes.cshtml
@{
    @model List<InformeLote>;

    <section class="align-items-center align-content-center MainFormProduc">
        <h2>Faltantes de inventario</h2>
       @if(Model.Count>0){
        <table class=" rounded-table table table-striped">
            <thead class="theadLocal bg-dark bg-gradient">
                <tr>
                    <th class="bg-dark" scope="col">Numero de lote</th>
                    <th class="bg-dark" scope="col">Producto</th>
                    <th class="bg-dark" scope="col">Cantidad en bodega</th>
                </tr>
            </thead>
            <tbody id="TableInventoryBody">
            @foreach(var faltante in Model){
                <tr>
                    <th scope="col">@faltante.Lote</th>
                    <th  scope="col">@faltante.Producto</th>
                    <th  scope="col">@faltante.Cantidad</th>
                </tr>
                }
            </tbody>
            </table>
        }
        else
        {
            <section class="d-flex justify-content-center align-items-center vh-100">
            <h2 class="p-5 text-dark">No se registran faltantes!</h2>
            </section>
        }
    </section>
}

WebStock/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <section class="MainMenu nav-justified d-inline-flex">
        <a asp-controller="Product" asp-action="Products">
        <section class="MenuItem align-items-center">
            <h6><strong>Registro</strong></h6>
            <img class="MenuIcon" src="~/src/img/registro.png" />
        </section>
        </a>
        <a asp-controller="Inventario" asp-action="Inventario">
            <section class="MenuItem align-items-center">
            <h6><strong>Inventario</strong></h6>
           <img class="MenuIcon" src="~/src/img/consulta.png"/>
            </section>
        </a>
        <a asp-controller="Salidas" asp-action="Salidas">
        <section class="MenuItem align-items-center">
            <h6><strong>Salidas</strong></h6>
            <img class="MenuIcon" src="~/src/img/bandeja-de-salida.png" />
        </section>
        </a>
        <a asp-controller="Faltantes" asp-action="Faltantes">
        <section class="MenuItem align-items-center">
            <h6><strong>Faltantes</strong></h6>
            <img class="MenuIcon" src="~/src/img/empty.png" />
        </section>
        </a>
    </section>
</div>

WebStock/Views/Inventario/Inventario.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model InformeLote;
    <section class="align-items-center align-content-center MainFormProduc">
        <h2>Consulta de inventario</h2>
        <section class="InventoryView">
            <br />
                <div class="mb-4 w-50">
                    <label for="ConsultNumLote" class="form-label">Lote</label>
                <input type="number" onchange="CheckForm()" class="form-control" required placeholder="Ingrese el nombre numero de lote" name="NumeroLote" id="ConsultNumLote">
                <small class="form-text text-muted">Dejá el espacio en blanco para obtener todos los productos en inventario</small>
                </div>

            <button id="btnSubmit" onclick="loadInventory()" type="button" class="btn btn-primary h-25">Verificar</button>
            
        </section>
        <table class=" rounded-table table table-striped">
            <thead class="theadLocal bg-dark bg-gradient">
                <tr>
                    <th class="bg-dark" scope="col">Numero de lote</th>
                    <th class="bg-dark" scope="col">Producto</th>
                    <th class="bg-dark" scope="col">Cantidad en bodega</th>
                    <th class="bg-dark" scope="col">Fecha de vencimiento</th>
                    <th class="bg-dark" scope="col">Estado</th>
                </tr>
            </thead>
            <tbody id="TableInventoryBody">
              
            </tbody>
        </table>


     
    </section>
}

WebStock/Views/Product/Products.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model ModelEntradaProducto;
    <section class="align-items-center align-content-center MainFormProduc">
    
    <section class="formView">
            <h2>Ingreso de productos</h2>
            <br />

            @using (Html.BeginForm("CreateProduct", "Product", FormMethod.Post, new { id = "FormProduct" }))
            {
                 <div class="mb-3">
                    <label for="NumLote" class="form-label">Número de lote a registrar</label>
                    <input onfocusout="GetLote()" onchange="CheckForm()" required type="number" name="producto.NumeroLote" value="@Model.producto.NumeroLote" class="form-control" id="NumLote">
                    <small class="form-text text-muted">Ingresá un lote existente para editar la información</small>
                    </div>

      <div class="mb-3">
       <label for="Product" class="form-label">Producto</label>
                    <input list="ProductsList" type="text" onchange="CheckForm()" class="form-control" required placeholder="Ingrese el nombre del producto" name="producto.Producto" value="@Model.producto.Producto" id="Product" aria-describedby="emailHelp">
                <datalist id="ProductsList">
                </datalist>    
      </div>
     
                <div class="mb-3">
                    <label for="Canti" class="form-label">Cantidad</label>
                    <input placeholder="Número de lote" onchange="CheckForm()" required type="number" name="producto.Cantidad" value="@Model.producto.Cantidad" class="form-control" id="Canti">
                </div>

        <div class="mb-3">
            <label for="DateFabri" class="form-label">Fecha de fabricación</label>
                    <input type="date" class="form-control" onchange="CheckForm()" required name="producto.FechaFabricacion" value="@Model.producto.FechaFabricacion" id="DateFabri">
        </div>

        <div class="mb-3">
            <label for="Provedor" class="form-label">Provedor</label>
                    <input list="ProvedorsList" onclick="loadProvedores()" onchange="CheckForm()" placeholder="Información completa del provedor" required name="producto.Provedor" value="@Model.producto.Provedor" type="text" class="form-control" id="Provedor">
                    <datalist id="ProvedorsList">
                </datalist>
                </div>

        <div class="mb-3">
            <label for="Caduca" class="form-label">Fecha de caducidad del lote</label>
                    <input type="date" class="form-control" onchange="CheckForm()" required name="producto.FechaCaducidad" value="@Model.producto.FechaCaducidad" id="Caduca">
        </div>

      <button id="btnSubmit" disabled="true" type="button" class="btn btn-primary">Registrar</button>
      }
    </section>
    @if(Model.messaje?.Length>0){
        <div class="modal" tabindex="-1">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 style="color:blue" class="modal-title" id="staticBackdropLabel">Resultado de la operación</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body align-content-center text-center" >
                    <h3 style="color:dimgray">@Model.messaje</h3>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-bs-dismiss="modal">De acuerdo</button>
                    </div>
                </div>
            </div>
        </div>
        }


    </section>
}

WebStock/Views/Salidas/Salidas.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model ModelSalidaProducto;
    <section class="align-items-center align-content-center MainFormProduc">

        <section class="formView">
            <h2>Movimiento de productos</h2>
            <br />

            @using (Html.BeginForm("MoverProducto", "Salidas", FormMethod.Post, new { id = "FormSalidas" }))
            {
                <div class="mb-3">
                    <label for="NumLote" class="form-label">Lote de producto</label>
                    <input onfocusout="GetLote()" onchange="CheckFormSalida()" required type="number" name="Salida.NumLote" value="@Model.Salida.NumLote" class="form-control" id="NumLote">
                </div>

                <div class="mb-3">
                    <label for="Product" class="form-label">Producto</label>
                    <input list="ProductsList" type="text" onchange="CheckFormSalida()" readonly class="form-control" required placeholder="Nombre del Producto" name="Salida.Producto" value="@Model.Salida.Producto" id="Product" aria-describedby="emailHelp">
                    <datalist id="ProductsList">
                    </datalist>
                </div>

                <div class="mb-3">
                    <label for="CantidSalida" class="form-label">Cantidad</label>
                    <input placeholder="Número de lote" onchange="CheckFormSalida()" required type="number" name="Salida.Cantidad" value="@Model.Salida.Cantidad" class="form-control" id="CantidSalida">
                </div>

                <div class="mb-3">
                    <label for="FechaSalida" class="form-label">Fecha de salida</label>
                    <input type="date" class="form-control" onchange="CheckFormSalida()" required name="Salida.Fecha_salida" value="@Model.Salida.Fecha_salida" id="FechaSalida">
                </div>

                <div class="mb-3">
                    <label for="Destino" class="form-label">Destino</label>
                    <input onchange="CheckFormSalida()" placeholder="Quién solicita el producto" required name="Salida.Destino" value="@Model.Salida.Destino" type="text" class="form-control" id="Destino">
                   
                </div>

                

                <button id="btnSubmitSalidas" disabled="true" type="submit" class="btn btn-primary">Registrar salida</button>
            }
        </section>
        @if (Model.messaje?.Length > 0)
        {
            <div class="modal" tabindex="-1">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 style="color:blue" class="modal-title" id="staticBackdropLabel">Resultado de la operación</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body align-content-center text-center">
                            <h3 style="color:dimgray">@Model.messaje</h3>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-bs-dismiss="modal">De acuerdo</button>
                        </div>
                    </div>
                </div>
            </div>
        }


    </section>
}

WebStock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebStock</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebStock.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><h2>WebStock</h2></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted WebFooter">
        <div class="container">
            &copy; 2023 - WebStock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>